1. BASIC JOIN (Sales + Customers)
SELECT
s.order_id,
c.customer_name,
s.profit,
s.sales,
c.region
FROM sales s
JOIN customers c
ON s.customer_id = c.customer_id;
INSIGHTS:
-This query combines customer details with sales data.
-It helps in understanding who purchased what and from which region.
-Useful for customer-level analysis and reporting.


2. SALES BY CATEGORY (Sales + Products)
SELECT
p.category,
SUM(s.sales) AS total_sales
FROM sales s
JOIN products p
ON s.product_id = p.product_id
GROUP BY p.category
ORDER BY total_sales DESC;
INSIGHTS:
-This shows total sales generated by each product category.
-Helps identify which category contributes most to revenue.
-Useful for product strategy and inventory planning.


3. CUSTOMER SALES BY REGION
SELECT
c.region,
c.customer_name,
SUM(s.sales) AS total_sales
FROM sales s
JOIN customers c
ON s.customer_id = c.customer_id
GROUP BY c.region, c.customer_name
ORDER BY total_sales DESC;
INSIGHTS:
-This identifies top customers in each region.
-Helps in recognizing high-value customers geographically.
-Useful for targeted marketing and customer retention strategies.


4. CATEGORY-WISE PROFIT (JOIN)
SELECT
p.category,
SUM(s.profit) AS total_profit
FROM sales s
JOIN products p
ON s.product_id = p.product_id
GROUP BY p.category
ORDER BY total_profit DESC;
INSIGHTS:
-This shows profit generated by each category.
-Helps identify most profitable product segments.
-Useful for focusing on high-margin categories.


5. TOP PRODUCT PER CATEGORY
SELECT category, product_name, total_sales
FROM (
    SELECT
    p.category,
    p.product_name,
    SUM(s.sales) AS total_sales,
    RANK() OVER (PARTITION BY p.category ORDER BY SUM(s.sales) DESC) AS rnk
FROM sales s
JOIN products p
ON s.product_id = p.product_id
GROUP BY p.category, p.product_name
) ranked
WHERE rnk = 1;
INSIGHTS:
-This identifies the best-selling product within each category.
-Helps in understanding category leaders.
-Useful for promotions, pricing, and inventory focus.


6. MULTIPLE JOIN (Customers + Products + Sales)
SELECT
c.customer_name,
p.category,
COUNT(s.order_id) AS orders
FROM sales s
JOIN customers c
ON s.customer_id = c.customer_id
JOIN products p
ON s.product_id = p.product_id
GROUP BY c.customer_name, p.category
ORDER BY orders DESC;
INSIGHTS:
-This shows what type of products each customer buys most.
-Helps in understanding customer preferences.
-Useful for personalized recommendations and cross-selling.


7. CUSTOMER LIFETIME VALUE
SELECT
c.customer_name,
SUM(s.sales) AS lifetime_value
FROM sales s
JOIN customers c ON s.customer_id = c.customer_id
GROUP BY c.customer_name
ORDER BY lifetime_value DESC;
INSIGHTS:
-High lifetime value customers contribute significantly to overall revenue and should be retained through targeted engagement strategies.


8. PROFIT MARGIN BY PRODUCT
SELECT 
p.product_name,
SUM(s.profit)/SUM(s.sales)*100 AS profit_margin
FROM sales s
JOIN products p ON s.product_id = p.product_id
GROUP BY p.product_name
ORDER BY profit_margin DESC;
INSIGHTS:
-Products with higher profit margins indicate better cost efficiency, while low-margin products may require pricing or cost optimization.


8. MONTHLY GROWTH
SELECT 
MONTHNAME(order_date) AS month,
SUM(sales) AS revenue
FROM sales
GROUP BY month
ORDER BY revenue DESC;
INSIGHTS:
-The monthly revenue trend highlights seasonal patterns, enabling better planning for inventory, marketing campaigns, and resource allocation.


SUMMARY:
By applying JOIN operations on multiple tables such as sales, customers, and products, a comprehensive analysis was performed to gain deeper business insights. The analysis enabled identification of high-value customers, regional performance variations, and category-wise revenue and profitability. It also highlighted top-performing products within each category and revealed customer purchasing patterns. These insights can support data-driven decision-making in areas such as marketing strategy, pricing optimization, inventory management, and customer retention.